// DO NOT EDIT!
// This file is generated by build/gen-nostr-mock-handlers.js

import type { RequestHandler, WebSocketHandler } from 'msw'
import mockActivityOnlines from '/@/nostr-mocks/handlers/activity/onlines/index'
import mockActivityTimeline from '/@/nostr-mocks/handlers/activity/timeline/index'
import mockBotsbotIdActionsActivate from '/@/nostr-mocks/handlers/bots/:botId/actions/activate/index'
import mockBotsbotIdActionsInactivate from '/@/nostr-mocks/handlers/bots/:botId/actions/inactivate/index'
import mockBotsbotIdActionsJoin from '/@/nostr-mocks/handlers/bots/:botId/actions/join/index'
import mockBotsbotIdActionsLeave from '/@/nostr-mocks/handlers/bots/:botId/actions/leave/index'
import mockBotsbotIdActionsReissue from '/@/nostr-mocks/handlers/bots/:botId/actions/reissue/index'
import mockBotsbotIdIcon from '/@/nostr-mocks/handlers/bots/:botId/icon/index'
import mockBotsbotId from '/@/nostr-mocks/handlers/bots/:botId/index'
import mockBotsbotIdLogs from '/@/nostr-mocks/handlers/bots/:botId/logs/index'
import mockBots from '/@/nostr-mocks/handlers/bots/index'
import mockBotsWs from '/@/nostr-mocks/handlers/bots/ws/index'
import mockChannelschannelIdBots from '/@/nostr-mocks/handlers/channels/:channelId/bots/index'
import mockChannelschannelIdEvents from '/@/nostr-mocks/handlers/channels/:channelId/events/index'
import mockChannelschannelId from '/@/nostr-mocks/handlers/channels/:channelId/index'
import mockChannelschannelIdMessages from '/@/nostr-mocks/handlers/channels/:channelId/messages/index'
import mockChannelschannelIdPins from '/@/nostr-mocks/handlers/channels/:channelId/pins/index'
import mockChannelschannelIdSubscribers from '/@/nostr-mocks/handlers/channels/:channelId/subscribers/index'
import mockChannelschannelIdTopic from '/@/nostr-mocks/handlers/channels/:channelId/topic/index'
import mockChannelschannelIdViewers from '/@/nostr-mocks/handlers/channels/:channelId/viewers/index'
import mockChannels from '/@/nostr-mocks/handlers/channels/index'
import mockClientsclientId from '/@/nostr-mocks/handlers/clients/:clientId/index'
import mockClientsclientIdTokens from '/@/nostr-mocks/handlers/clients/:clientId/tokens/index'
import mockClients from '/@/nostr-mocks/handlers/clients/index'
import mockClipfoldersfolderId from '/@/nostr-mocks/handlers/clip-folders/:folderId/index'
import mockClipfoldersfolderIdMessagesmessageId from '/@/nostr-mocks/handlers/clip-folders/:folderId/messages/:messageId/index'
import mockClipfoldersfolderIdMessages from '/@/nostr-mocks/handlers/clip-folders/:folderId/messages/index'
import mockClipfolders from '/@/nostr-mocks/handlers/clip-folders/index'
import mockFilesfileId from '/@/nostr-mocks/handlers/files/:fileId/index'
import mockFilesfileIdMeta from '/@/nostr-mocks/handlers/files/:fileId/meta/index'
import mockFilesfileIdThumbnail from '/@/nostr-mocks/handlers/files/:fileId/thumbnail/index'
import mockFiles from '/@/nostr-mocks/handlers/files/index'
import mockGroupsgroupIdAdminsuserId from '/@/nostr-mocks/handlers/groups/:groupId/admins/:userId/index'
import mockGroupsgroupIdAdmins from '/@/nostr-mocks/handlers/groups/:groupId/admins/index'
import mockGroupsgroupIdIcon from '/@/nostr-mocks/handlers/groups/:groupId/icon/index'
import mockGroupsgroupId from '/@/nostr-mocks/handlers/groups/:groupId/index'
import mockGroupsgroupIdMembersuserId from '/@/nostr-mocks/handlers/groups/:groupId/members/:userId/index'
import mockGroupsgroupIdMembers from '/@/nostr-mocks/handlers/groups/:groupId/members/index'
import mockGroups from '/@/nostr-mocks/handlers/groups/index'
import mockLogin from '/@/nostr-mocks/handlers/login/index'
import mockLogout from '/@/nostr-mocks/handlers/logout/index'
import mockMessagesmessageIdClips from '/@/nostr-mocks/handlers/messages/:messageId/clips/index'
import mockMessagesmessageId from '/@/nostr-mocks/handlers/messages/:messageId/index'
import mockMessagesmessageIdPin from '/@/nostr-mocks/handlers/messages/:messageId/pin/index'
import mockMessagesmessageIdStampsstampId from '/@/nostr-mocks/handlers/messages/:messageId/stamps/:stampId/index'
import mockMessagesmessageIdStamps from '/@/nostr-mocks/handlers/messages/:messageId/stamps/index'
import mockMessages from '/@/nostr-mocks/handlers/messages/index'
import mockOauth2AuthorizeDecide from '/@/nostr-mocks/handlers/oauth2/authorize/decide/index'
import mockOauth2Authorize from '/@/nostr-mocks/handlers/oauth2/authorize/index'
import mockOauth2Revoke from '/@/nostr-mocks/handlers/oauth2/revoke/index'
import mockOauth2Token from '/@/nostr-mocks/handlers/oauth2/token/index'
import mockOgpCache from '/@/nostr-mocks/handlers/ogp/cache/index'
import mockOgp from '/@/nostr-mocks/handlers/ogp/index'
import mockPublicIconusername from '/@/nostr-mocks/handlers/public/icon/:username/index'
import mockStamppalettespaletteId from '/@/nostr-mocks/handlers/stamp-palettes/:paletteId/index'
import mockStamppalettes from '/@/nostr-mocks/handlers/stamp-palettes/index'
import mockStampsstampIdImage from '/@/nostr-mocks/handlers/stamps/:stampId/image/index'
import mockStampsstampId from '/@/nostr-mocks/handlers/stamps/:stampId/index'
import mockStampsstampIdStats from '/@/nostr-mocks/handlers/stamps/:stampId/stats/index'
import mockStamps from '/@/nostr-mocks/handlers/stamps/index'
import mockTagstagId from '/@/nostr-mocks/handlers/tags/:tagId/index'
import mockUsersuserIdDmchannel from '/@/nostr-mocks/handlers/users/:userId/dm-channel/index'
import mockUsersuserIdIcon from '/@/nostr-mocks/handlers/users/:userId/icon/index'
import mockUsersuserId from '/@/nostr-mocks/handlers/users/:userId/index'
import mockUsersuserIdMessages from '/@/nostr-mocks/handlers/users/:userId/messages/index'
import mockUsersuserIdPassword from '/@/nostr-mocks/handlers/users/:userId/password/index'
import mockUsersuserIdStats from '/@/nostr-mocks/handlers/users/:userId/stats/index'
import mockUsersuserIdTagstagId from '/@/nostr-mocks/handlers/users/:userId/tags/:tagId/index'
import mockUsersuserIdTags from '/@/nostr-mocks/handlers/users/:userId/tags/index'
import mockUsers from '/@/nostr-mocks/handlers/users/index'
import mockUsersMeExaccounts from '/@/nostr-mocks/handlers/users/me/ex-accounts/index'
import mockUsersMeExaccountsLink from '/@/nostr-mocks/handlers/users/me/ex-accounts/link/index'
import mockUsersMeExaccountsUnlink from '/@/nostr-mocks/handlers/users/me/ex-accounts/unlink/index'
import mockUsersMeFcmdevice from '/@/nostr-mocks/handlers/users/me/fcm-device/index'
import mockUsersMeIcon from '/@/nostr-mocks/handlers/users/me/icon/index'
import mockUsersMe from '/@/nostr-mocks/handlers/users/me/index'
import mockUsersMeOidc from '/@/nostr-mocks/handlers/users/me/oidc/index'
import mockUsersMePassword from '/@/nostr-mocks/handlers/users/me/password/index'
import mockUsersMeQrcode from '/@/nostr-mocks/handlers/users/me/qr-code/index'
import mockUsersMeSessionssessionId from '/@/nostr-mocks/handlers/users/me/sessions/:sessionId/index'
import mockUsersMeSessions from '/@/nostr-mocks/handlers/users/me/sessions/index'
import mockUsersMeSettings from '/@/nostr-mocks/handlers/users/me/settings/index'
import mockUsersMeSettingsNotifycitation from '/@/nostr-mocks/handlers/users/me/settings/notify-citation/index'
import mockUsersMeStamphistory from '/@/nostr-mocks/handlers/users/me/stamp-history/index'
import mockUsersMeStarschannelId from '/@/nostr-mocks/handlers/users/me/stars/:channelId/index'
import mockUsersMeStars from '/@/nostr-mocks/handlers/users/me/stars/index'
import mockUsersMeSubscriptionschannelId from '/@/nostr-mocks/handlers/users/me/subscriptions/:channelId/index'
import mockUsersMeSubscriptions from '/@/nostr-mocks/handlers/users/me/subscriptions/index'
import mockUsersMeTagstagId from '/@/nostr-mocks/handlers/users/me/tags/:tagId/index'
import mockUsersMeTags from '/@/nostr-mocks/handlers/users/me/tags/index'
import mockUsersMeTokenstokenId from '/@/nostr-mocks/handlers/users/me/tokens/:tokenId/index'
import mockUsersMeTokens from '/@/nostr-mocks/handlers/users/me/tokens/index'
import mockUsersMeUnreadchannelId from '/@/nostr-mocks/handlers/users/me/unread/:channelId/index'
import mockUsersMeUnread from '/@/nostr-mocks/handlers/users/me/unread/index'
import mockUsersMeViewstates from '/@/nostr-mocks/handlers/users/me/view-states/index'
import mockVersion from '/@/nostr-mocks/handlers/version/index'
import mockWebhookswebhookIdIcon from '/@/nostr-mocks/handlers/webhooks/:webhookId/icon/index'
import mockWebhookswebhookId from '/@/nostr-mocks/handlers/webhooks/:webhookId/index'
import mockWebhookswebhookIdMessages from '/@/nostr-mocks/handlers/webhooks/:webhookId/messages/index'
import mockWebhooks from '/@/nostr-mocks/handlers/webhooks/index'
import mockWebrtcAuthenticate from '/@/nostr-mocks/handlers/webrtc/authenticate/index'
import mockWebrtcState from '/@/nostr-mocks/handlers/webrtc/state/index'
import mockWs from '/@/nostr-mocks/handlers/ws/index'

export const handlers: Array<RequestHandler | WebSocketHandler> = [
  ...mockActivityOnlines,
  ...mockActivityTimeline,
  ...mockBotsbotIdActionsActivate,
  ...mockBotsbotIdActionsInactivate,
  ...mockBotsbotIdActionsJoin,
  ...mockBotsbotIdActionsLeave,
  ...mockBotsbotIdActionsReissue,
  ...mockBotsbotIdIcon,
  ...mockBotsbotId,
  ...mockBotsbotIdLogs,
  ...mockBots,
  ...mockBotsWs,
  ...mockChannelschannelIdBots,
  ...mockChannelschannelIdEvents,
  ...mockChannelschannelId,
  ...mockChannelschannelIdMessages,
  ...mockChannelschannelIdPins,
  ...mockChannelschannelIdSubscribers,
  ...mockChannelschannelIdTopic,
  ...mockChannelschannelIdViewers,
  ...mockChannels,
  ...mockClientsclientId,
  ...mockClientsclientIdTokens,
  ...mockClients,
  ...mockClipfoldersfolderId,
  ...mockClipfoldersfolderIdMessagesmessageId,
  ...mockClipfoldersfolderIdMessages,
  ...mockClipfolders,
  ...mockFilesfileId,
  ...mockFilesfileIdMeta,
  ...mockFilesfileIdThumbnail,
  ...mockFiles,
  ...mockGroupsgroupIdAdminsuserId,
  ...mockGroupsgroupIdAdmins,
  ...mockGroupsgroupIdIcon,
  ...mockGroupsgroupId,
  ...mockGroupsgroupIdMembersuserId,
  ...mockGroupsgroupIdMembers,
  ...mockGroups,
  ...mockLogin,
  ...mockLogout,
  ...mockMessagesmessageIdClips,
  ...mockMessagesmessageId,
  ...mockMessagesmessageIdPin,
  ...mockMessagesmessageIdStampsstampId,
  ...mockMessagesmessageIdStamps,
  ...mockMessages,
  ...mockOauth2AuthorizeDecide,
  ...mockOauth2Authorize,
  ...mockOauth2Revoke,
  ...mockOauth2Token,
  ...mockOgpCache,
  ...mockOgp,
  ...mockPublicIconusername,
  ...mockStamppalettespaletteId,
  ...mockStamppalettes,
  ...mockStampsstampIdImage,
  ...mockStampsstampId,
  ...mockStampsstampIdStats,
  ...mockStamps,
  ...mockTagstagId,
  ...mockUsersuserIdDmchannel,
  ...mockUsersuserIdIcon,
  ...mockUsersuserId,
  ...mockUsersuserIdMessages,
  ...mockUsersuserIdPassword,
  ...mockUsersuserIdStats,
  ...mockUsersuserIdTagstagId,
  ...mockUsersuserIdTags,
  ...mockUsers,
  ...mockUsersMeExaccounts,
  ...mockUsersMeExaccountsLink,
  ...mockUsersMeExaccountsUnlink,
  ...mockUsersMeFcmdevice,
  ...mockUsersMeIcon,
  ...mockUsersMe,
  ...mockUsersMeOidc,
  ...mockUsersMePassword,
  ...mockUsersMeQrcode,
  ...mockUsersMeSessionssessionId,
  ...mockUsersMeSessions,
  ...mockUsersMeSettings,
  ...mockUsersMeSettingsNotifycitation,
  ...mockUsersMeStamphistory,
  ...mockUsersMeStarschannelId,
  ...mockUsersMeStars,
  ...mockUsersMeSubscriptionschannelId,
  ...mockUsersMeSubscriptions,
  ...mockUsersMeTagstagId,
  ...mockUsersMeTags,
  ...mockUsersMeTokenstokenId,
  ...mockUsersMeTokens,
  ...mockUsersMeUnreadchannelId,
  ...mockUsersMeUnread,
  ...mockUsersMeViewstates,
  ...mockVersion,
  ...mockWebhookswebhookIdIcon,
  ...mockWebhookswebhookId,
  ...mockWebhookswebhookIdMessages,
  ...mockWebhooks,
  ...mockWebrtcAuthenticate,
  ...mockWebrtcState,
  ...mockWs
]
