// DO NOT EDIT!
// This file is generated by build/gen-nostr-mock-handlers.js
// Run 'node build/gen-nostr-mock-handlers.js' to regenerate this file

import handler0 from '/@/nostr-mocks/handlers/ws'
import handler1 from '/@/nostr-mocks/handlers/webrtc/state'
import handler2 from '/@/nostr-mocks/handlers/webrtc/authenticate'
import handler3 from '/@/nostr-mocks/handlers/webhooks/[webhookId]/messages'
import handler4 from '/@/nostr-mocks/handlers/webhooks/[webhookId]/icon'
import handler5 from '/@/nostr-mocks/handlers/webhooks/[webhookId]'
import handler6 from '/@/nostr-mocks/handlers/webhooks'
import handler7 from '/@/nostr-mocks/handlers/version'
import handler8 from '/@/nostr-mocks/handlers/users/me/view-states'
import handler9 from '/@/nostr-mocks/handlers/users/me/unread/[channelId]'
import handler10 from '/@/nostr-mocks/handlers/users/me/unread'
import handler11 from '/@/nostr-mocks/handlers/users/me/tokens/[tokenId]'
import handler12 from '/@/nostr-mocks/handlers/users/me/tokens'
import handler13 from '/@/nostr-mocks/handlers/users/me/tags/[tagId]'
import handler14 from '/@/nostr-mocks/handlers/users/me/tags'
import handler15 from '/@/nostr-mocks/handlers/users/me/subscriptions/[channelId]'
import handler16 from '/@/nostr-mocks/handlers/users/me/subscriptions'
import handler17 from '/@/nostr-mocks/handlers/users/me/stars/[channelId]'
import handler18 from '/@/nostr-mocks/handlers/users/me/stars'
import handler19 from '/@/nostr-mocks/handlers/users/me/stamp-history'
import handler20 from '/@/nostr-mocks/handlers/users/me/settings/notify-citation'
import handler21 from '/@/nostr-mocks/handlers/users/me/settings'
import handler22 from '/@/nostr-mocks/handlers/users/me/sessions/[sessionId]'
import handler23 from '/@/nostr-mocks/handlers/users/me/sessions'
import handler24 from '/@/nostr-mocks/handlers/users/me/qr-code'
import handler25 from '/@/nostr-mocks/handlers/users/me/password'
import handler26 from '/@/nostr-mocks/handlers/users/me/oidc'
import handler27 from '/@/nostr-mocks/handlers/users/me/icon'
import handler28 from '/@/nostr-mocks/handlers/users/me/fcm-device'
import handler29 from '/@/nostr-mocks/handlers/users/me/ex-accounts/unlink'
import handler30 from '/@/nostr-mocks/handlers/users/me/ex-accounts/link'
import handler31 from '/@/nostr-mocks/handlers/users/me/ex-accounts'
import handler32 from '/@/nostr-mocks/handlers/users/me'
import handler33 from '/@/nostr-mocks/handlers/users/[userId]/tags/[tagId]'
import handler34 from '/@/nostr-mocks/handlers/users/[userId]/tags'
import handler35 from '/@/nostr-mocks/handlers/users/[userId]/stats'
import handler36 from '/@/nostr-mocks/handlers/users/[userId]/password'
import handler37 from '/@/nostr-mocks/handlers/users/[userId]/messages'
import handler38 from '/@/nostr-mocks/handlers/users/[userId]/icon'
import handler39 from '/@/nostr-mocks/handlers/users/[userId]/dm-channel'
import handler40 from '/@/nostr-mocks/handlers/users/[userId]'
import handler41 from '/@/nostr-mocks/handlers/users'
import handler42 from '/@/nostr-mocks/handlers/tags/[tagId]'
import handler43 from '/@/nostr-mocks/handlers/stamps/[stampId]/stats'
import handler44 from '/@/nostr-mocks/handlers/stamps/[stampId]/image'
import handler45 from '/@/nostr-mocks/handlers/stamps/[stampId]'
import handler46 from '/@/nostr-mocks/handlers/stamps'
import handler47 from '/@/nostr-mocks/handlers/stamp-palettes/[paletteId]'
import handler48 from '/@/nostr-mocks/handlers/stamp-palettes'
import handler49 from '/@/nostr-mocks/handlers/public/icon/[username]'
import handler50 from '/@/nostr-mocks/handlers/ogp/cache'
import handler51 from '/@/nostr-mocks/handlers/ogp'
import handler52 from '/@/nostr-mocks/handlers/oauth2/token'
import handler53 from '/@/nostr-mocks/handlers/oauth2/revoke'
import handler54 from '/@/nostr-mocks/handlers/oauth2/authorize/decide'
import handler55 from '/@/nostr-mocks/handlers/oauth2/authorize'
import handler56 from '/@/nostr-mocks/handlers/messages/[messageId]/stamps/[stampId]'
import handler57 from '/@/nostr-mocks/handlers/messages/[messageId]/stamps'
import handler58 from '/@/nostr-mocks/handlers/messages/[messageId]/pin'
import handler59 from '/@/nostr-mocks/handlers/messages/[messageId]/clips'
import handler60 from '/@/nostr-mocks/handlers/messages/[messageId]'
import handler61 from '/@/nostr-mocks/handlers/messages'
import handler62 from '/@/nostr-mocks/handlers/logout'
import handler63 from '/@/nostr-mocks/handlers/login'
import handler64 from '/@/nostr-mocks/handlers/groups/[groupId]/members/[userId]'
import handler65 from '/@/nostr-mocks/handlers/groups/[groupId]/members'
import handler66 from '/@/nostr-mocks/handlers/groups/[groupId]/icon'
import handler67 from '/@/nostr-mocks/handlers/groups/[groupId]/admins/[userId]'
import handler68 from '/@/nostr-mocks/handlers/groups/[groupId]/admins'
import handler69 from '/@/nostr-mocks/handlers/groups/[groupId]'
import handler70 from '/@/nostr-mocks/handlers/groups'
import handler71 from '/@/nostr-mocks/handlers/files/[fileId]/thumbnail'
import handler72 from '/@/nostr-mocks/handlers/files/[fileId]/meta'
import handler73 from '/@/nostr-mocks/handlers/files/[fileId]'
import handler74 from '/@/nostr-mocks/handlers/files'
import handler75 from '/@/nostr-mocks/handlers/clip-folders/[folderId]/messages/[messageId]'
import handler76 from '/@/nostr-mocks/handlers/clip-folders/[folderId]/messages'
import handler77 from '/@/nostr-mocks/handlers/clip-folders/[folderId]'
import handler78 from '/@/nostr-mocks/handlers/clip-folders'
import handler79 from '/@/nostr-mocks/handlers/clients/[clientId]/tokens'
import handler80 from '/@/nostr-mocks/handlers/clients/[clientId]'
import handler81 from '/@/nostr-mocks/handlers/clients'
import handler82 from '/@/nostr-mocks/handlers/channels/[channelId]/viewers'
import handler83 from '/@/nostr-mocks/handlers/channels/[channelId]/topic'
import handler84 from '/@/nostr-mocks/handlers/channels/[channelId]/subscribers'
import handler85 from '/@/nostr-mocks/handlers/channels/[channelId]/pins'
import handler86 from '/@/nostr-mocks/handlers/channels/[channelId]/messages'
import handler87 from '/@/nostr-mocks/handlers/channels/[channelId]/events'
import handler88 from '/@/nostr-mocks/handlers/channels/[channelId]/bots'
import handler89 from '/@/nostr-mocks/handlers/channels/[channelId]'
import handler90 from '/@/nostr-mocks/handlers/channels'
import handler91 from '/@/nostr-mocks/handlers/bots/ws'
import handler92 from '/@/nostr-mocks/handlers/bots/[botId]/logs'
import handler93 from '/@/nostr-mocks/handlers/bots/[botId]/icon'
import handler94 from '/@/nostr-mocks/handlers/bots/[botId]/actions/reissue'
import handler95 from '/@/nostr-mocks/handlers/bots/[botId]/actions/leave'
import handler96 from '/@/nostr-mocks/handlers/bots/[botId]/actions/join'
import handler97 from '/@/nostr-mocks/handlers/bots/[botId]/actions/inactivate'
import handler98 from '/@/nostr-mocks/handlers/bots/[botId]/actions/activate'
import handler99 from '/@/nostr-mocks/handlers/bots/[botId]'
import handler100 from '/@/nostr-mocks/handlers/bots'
import handler101 from '/@/nostr-mocks/handlers/activity/timeline'
import handler102 from '/@/nostr-mocks/handlers/activity/onlines'

export const handlers = [
  handler0,
  handler1,
  handler2,
  handler3,
  handler4,
  handler5,
  handler6,
  handler7,
  handler8,
  handler9,
  handler10,
  handler11,
  handler12,
  handler13,
  handler14,
  handler15,
  handler16,
  handler17,
  handler18,
  handler19,
  handler20,
  handler21,
  handler22,
  handler23,
  handler24,
  handler25,
  handler26,
  handler27,
  handler28,
  handler29,
  handler30,
  handler31,
  handler32,
  handler33,
  handler34,
  handler35,
  handler36,
  handler37,
  handler38,
  handler39,
  handler40,
  handler41,
  handler42,
  handler43,
  handler44,
  handler45,
  handler46,
  handler47,
  handler48,
  handler49,
  handler50,
  handler51,
  handler52,
  handler53,
  handler54,
  handler55,
  handler56,
  handler57,
  handler58,
  handler59,
  handler60,
  handler61,
  handler62,
  handler63,
  handler64,
  handler65,
  handler66,
  handler67,
  handler68,
  handler69,
  handler70,
  handler71,
  handler72,
  handler73,
  handler74,
  handler75,
  handler76,
  handler77,
  handler78,
  handler79,
  handler80,
  handler81,
  handler82,
  handler83,
  handler84,
  handler85,
  handler86,
  handler87,
  handler88,
  handler89,
  handler90,
  handler91,
  handler92,
  handler93,
  handler94,
  handler95,
  handler96,
  handler97,
  handler98,
  handler99,
  handler100,
  handler101,
  handler102
].flat()
